In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

In [12]:
repo_path = os.path.dirname(os.path.abspath(""))
dataset = pd.read_csv(os.path.join(repo_path, "dbs", "DatasetAfricaMalaria.csv"))

In [16]:
dataset

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)",...,Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
0,Algeria,2007,DZA,0.01,26.0,NaN,NaN,NaN,NaN,NaN,...,2.71,91.68,85.83,94.78,85.85,76.94,90.57,28.033886,1.659626,POINT (28.033886 1.659626)
1,Angola,2007,AGO,286.72,1533485.0,18.0,29.8,1.5,NaN,NaN,...,5.01,47.96,23.77,65.83,37.26,14.00,54.44,-11.202692,17.873887,POINT (-11.202692 17.873887)
2,Benin,2007,BEN,480.24,0.0,NaN,NaN,NaN,NaN,NaN,...,4.09,63.78,54.92,76.24,11.80,4.29,22.36,9.307690,2.315834,POINT (9.307689999999999 2.315834)
3,Botswana,2007,BWA,1.03,390.0,NaN,NaN,NaN,NaN,NaN,...,4.80,78.89,57.60,94.35,61.60,39.99,77.30,-22.328474,24.684866,POINT (-22.328474 24.684866)
4,Burkina Faso,2007,BFA,503.80,44246.0,NaN,NaN,NaN,NaN,NaN,...,5.91,52.27,45.13,76.15,15.60,6.38,46.49,12.238333,-1.561593,POINT (12.238333 -1.561593)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,Togo,2017,TGO,278.20,1755577.0,69.7,31.1,41.7,NaN,NaN,...,3.79,65.13,48.39,89.06,16.13,7.40,28.61,8.619543,0.824782,POINT (8.619543 0.824782)
590,Tunisia,2017,TUN,NaN,NaN,NaN,NaN,NaN,92.66,NaN,...,1.57,96.25,88.71,99.70,90.92,81.35,95.29,33.886917,9.537499,POINT (33.886917 9.537499)
591,Uganda,2017,UGA,336.76,11667831.0,NaN,NaN,NaN,7.07,4.46,...,6.25,49.10,41.25,75.11,18.47,16.17,26.11,1.373333,32.290275,POINT (1.373333 32.290275)
592,Zambia,2017,ZMB,160.05,5505639.0,NaN,NaN,NaN,NaN,NaN,...,4.21,59.96,41.95,83.86,26.37,18.93,36.24,-13.133897,27.849332,POINT (-13.133897 27.849332)
593,Zimbabwe,2017,ZWE,108.55,467508.0,NaN,NaN,NaN,NaN,NaN,...,1.28,64.05,49.80,94.00,36.22,31.47,46.22,-19.015438,29.154857,POINT (-19.015438 29.154857)

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 27 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Country Name                                                                             594 non-null    object
 1   Year                                                                                     594 non-null    int64
 2   Country Code                                                                             594 non-null    object
 3   Incidence of malaria (per 1,000 population at risk)                                      550 non-null    float64
 4   Malaria cases reported                                                                   550 non-null    float64
 5   Use of insecticide-treated bed nets (% of under-5 population)                            132 non-null    float64
 6   Children with fever receiving antimalarial drugs (% of children under age 5 with fever)  122 non-null    float64
 7   Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)    106 non-null    float64
 8   People using safely managed drinking water services (% of population)                    99 non-null     float64
 9   People using safely managed drinking water services, rural (% of rural population)       88 non-null     float64
 10  People using safely managed drinking water services, urban (% of urban population)       176 non-null    float64
 11  People using safely managed sanitation services (% of population)                        132 non-null    float64
 12  People using safely managed sanitation services, rural (% of rural population)           110 non-null    float64
 13  People using safely managed sanitation services, urban  (% of urban population)          132 non-null    float64
 14  Rural population (% of total population)                                                 588 non-null    float64
 15  Rural population growth (annual %)                                                       588 non-null    float64
 16  Urban population (% of total population)                                                 588 non-null    float64
 17  Urban population growth (annual %)                                                       588 non-null    float64
 18  People using at least basic drinking water services (% of population)                    588 non-null    float64
 19  People using at least basic drinking water services, rural (% of rural population)       566 non-null    float64
 20  People using at least basic drinking water services, urban (% of urban population)       566 non-null    float64
 21  People using at least basic sanitation services (% of population)                        588 non-null    float64
 22  People using at least basic sanitation services, rural (% of rural population)           566 non-null    float64
 23  People using at least basic sanitation services, urban  (% of urban population)          566 non-null    float64
 24  latitude                                                                                 594 non-null    float64
 25  longitude                                                                                594 non-null    float64
 26  geometry                                                                                 594 non-null    object
dtypes: float64(23), int64(1), object(3)
memory usage: 125.4+ KB

In [18]:
df_selected = dataset[[
    "Year", 
    "Country Name", 
    "Incidence of malaria (per 1,000 population at risk)", 
    "Urban population (% of total population)",
    "People using at least basic drinking water services (% of population)",
    "People using at least basic sanitation services (% of population)"]]
df_selected

,Year,Country Name,"Incidence of malaria (per 1,000 population at risk)",Urban population (% of total population),People using at least basic drinking water services (% of population),People using at least basic sanitation services (% of population)
0,2007,Algeria,0.01,65.35,91.68,85.85
1,2007,Angola,286.72,57.52,47.96,37.26
2,2007,Benin,480.24,41.56,63.78,11.80
3,2007,Botswana,1.03,57.93,78.89,61.60
4,2007,Burkina Faso,503.80,23.00,52.27,15.60
...,...,...,...,...,...,...
589,2017,Togo,278.20,41.16,65.13,16.13
590,2017,Tunisia,NaN,68.64,96.25,90.92
591,2017,Uganda,336.76,23.20,49.10,18.47
592,2017,Zambia,160.05,42.98,59.96,26.37
593,2017,Zimbabwe,108.55,32.24,64.05,36.22

In [19]:
df_selected = df_selected.fillna("NaN")

In [20]:
df_test = df_selected[(df_selected["Incidence of malaria (per 1,000 population at risk)"] == "NaN")]
countries = df_test["Country Name"].unique()
countries

array(['Lesotho', 'Mauritius', 'Seychelles', 'Tunisia'], dtype=object)

In [21]:
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 6 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Year                                                                   594 non-null    int64
 1   Country Name                                                           594 non-null    object
 2   Incidence of malaria (per 1,000 population at risk)                    594 non-null    object
 3   Urban population (% of total population)                               594 non-null    object
 4   People using at least basic drinking water services (% of population)  594 non-null    object
 5   People using at least basic sanitation services (% of population)      594 non-null    object
dtypes: int64(1), object(5)
memory usage: 28.0+ KB

In [22]:
df_selected_filtered = df_selected[~df_selected["Country Name"].isin(countries)].reset_index(drop=True)
df_selected_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 6 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Year                                                                   550 non-null    int64
 1   Country Name                                                           550 non-null    object
 2   Incidence of malaria (per 1,000 population at risk)                    550 non-null    object
 3   Urban population (% of total population)                               550 non-null    object
 4   People using at least basic drinking water services (% of population)  550 non-null    object
 5   People using at least basic sanitation services (% of population)      550 non-null    object
dtypes: int64(1), object(5)
memory usage: 25.9+ KB

In [23]:
df_selected_filtered

,Year,Country Name,"Incidence of malaria (per 1,000 population at risk)",Urban population (% of total population),People using at least basic drinking water services (% of population),People using at least basic sanitation services (% of population)
0,2007,Algeria,0.01,65.35,91.68,85.85
1,2007,Angola,286.72,57.52,47.96,37.26
2,2007,Benin,480.24,41.56,63.78,11.8
3,2007,Botswana,1.03,57.93,78.89,61.6
4,2007,Burkina Faso,503.8,23.0,52.27,15.6
...,...,...,...,...,...,...
545,2017,Tanzania,123.96,33.05,56.73,29.91
546,2017,Togo,278.2,41.16,65.13,16.13
547,2017,Uganda,336.76,23.2,49.1,18.47
548,2017,Zambia,160.05,42.98,59.96,26.37
549,2017,Zimbabwe,108.55,32.24,64.05,36.22

In [24]:
d_year = {f"{y}": df_selected_filtered[df_selected_filtered["Year"] == y] for y in df_selected_filtered["Year"].unique()}
for year, df_year in d_year.items():

    n = df_year["Country Name"].nunique()
    print(f"Año: {year} - Cantidad de países: {n}")

    # Averiguar si existe un 'NaN' en el dataframe
    if (df_year["Incidence of malaria (per 1,000 population at risk)"] == "NaN").any():
        print(df_year["Year"].iloc[0])

Año: 2007 - Cantidad de países: 50
Año: 2008 - Cantidad de países: 50
Año: 2009 - Cantidad de países: 50
Año: 2010 - Cantidad de países: 50
Año: 2011 - Cantidad de países: 50
Año: 2012 - Cantidad de países: 50
Año: 2013 - Cantidad de países: 50
Año: 2014 - Cantidad de países: 50
Año: 2015 - Cantidad de países: 50
Año: 2016 - Cantidad de países: 50
Año: 2017 - Cantidad de países: 50

In [25]:
d_year["2012"].head(12)

,Year,Country Name,"Incidence of malaria (per 1,000 population at risk)",Urban population (% of total population),People using at least basic drinking water services (% of population),People using at least basic sanitation services (% of population)
250,2012,Algeria,0.03,68.92,92.84,86.97
251,2012,Angola,174.43,61.27,51.97,43.59
252,2012,Benin,378.03,44.13,65.26,14.51
253,2012,Botswana,0.22,64.77,85.42,70.15
254,2012,Burkina Faso,527.54,25.77,49.92,17.79
255,2012,Burundi,153.93,11.19,57.74,45.92
256,2012,Cabo Verde,0.01,62.82,84.01,64.78
257,2012,Cameroon,245.13,52.77,60.28,38.93
258,2012,Central African Republic,413.09,39.39,45.95,24.83
259,2012,Chad,195.34,22.14,39.49,9.71
260,2012,Comoros,68.85,28.12,81.79,34.69
261,2012,"Congo, Dem. Rep.",363.0,41.08,40.65,20.48

# Ideas de investigación

## Opción 1 - Análisis de correlación multivariable para un año dado

El objetivo es analizar si existe una correlación entre la incidencia de malaria con población urbana, acceso al agua potable y acceso a servicios de sanidad.

## Opción 2 - Análisis de correlación simple para un año dado

El objetivo es analizar si existe una correlación entre la incidencia de malaria con acceso al agua potable.

## Comentario

- Saneamiento de datos.
- Preguntar cómo agrupar la información de los distintos países.
- Cómo aprovechar la información de todos los años.
- Cómo hacer un análisis entre dos años distintos.